# Generated by Django 5.0.2 on 2024-04-10 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='repo_name',
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome',
            field=models.CharField(default='aluno teste', max_length=50),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(default='turma', max_length=50),
        ),
        migrations.CreateModel(
            name='AlunoQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=50)),
                ('nota', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.aluno')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.questao')),
            ],
        ),
    ]
